name: CI Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: # Add your command for running unit tests here

    - name: Run Coverage
      run: # Add your command for running coverage here
      id: coverage

    - name: Auto Make Coverage
      if: failure() && steps.coverage.outcome == 'failure'
      run: # Add your command for auto making coverage here

    - name: Rerun Coverage
      if: always() && steps.coverage.outcome == 'failure'
      run: # Add your command for rerunning coverage here

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: # Add your command for build here
      id: build

    - name: Autoheal
      if: failure() && steps.build.outcome == 'failure'
      run: # Add your command for autoheal here

    - name: Rebuild
      if: always() && steps.build.outcome == 'failure'
      run: # Add your command for rebuild here

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: # Add your command for deploy here
