name: CI Workflow

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: # Add your command for running unit tests here

  run-coverage:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Coverage
        run: # Add your command for running coverage here
        id: coverage

  autoheal-tests:
    needs: run-coverage
    if: failure() && needs.run-coverage.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Autoheal Tests
        run: # Add your command for autohealing tests here