name: CI Workflow

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Run Unit Tests
        run: mvn clean test

  run-coverage:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run JaCoCo Code Coverage
        run: mvn clean verify -DskipTests -Ddependency-check.skip=true


  autoheal-tests:
    needs: run-coverage
    if: failure() && needs.run-coverage.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Autoheal Tests
        run: echo "Autohealing tests..." # Replace with your autoheal test command

  comit-changes:
    needs: autoheal-tests
    if: failure() && needs.run-coverage.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit Changes
        run: echo "Commiting Changes..." # Replace with your autoheal test command