name: Feature Workflow improvement

on:
    workflow_dispatch:


jobs:
  super-lint:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: '^target/.*'

   
  scan_dependency:
    runs-on: ubuntu-latest
    needs: super-lint

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        node-version: 16
    - name: Build with Maven
      run: mvn dependency-check:check -DskipTests 

  run_coverage:
    runs-on: ubuntu-latest
    needs: scan_dependency

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        node-version: 16
    - name: Calculate code coverage
      run: mvn clean verify jacoco:report "-Ddependency-check.skip=true"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: target/site/jacoco/
        retention-days: 7 