name: My Workflow

on:
  push:
    branches-ignore:
      - 'master'


jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: ^src/.*

  run_unit_tests:
    runs-on: ubuntu-latest
    needs: super-lint

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: mvn -B test --file pom.xml

  run_coverage:
    runs-on: ubuntu-latest
    needs: run_unit_tests

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Calculate code coverage
      run: mvn -B jacoco:prepare-agent test jacoco:report --file pom.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: target/site/jacoco/
        retention-days: 7
