on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  postman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Wait for 10 seconds
        run: sleep 10s

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install newman
        run: npm install -g newman

      - name: List files and directories
        run: |
          ls -al
          ls -al src/test
          ls -al src/test/Postman_Tests

      - name: Run Postman tests
        run: newman run src/test/Postman_Tests/Calculate.postman_collection.json
