name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  run-selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
            path: ~\.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

      - name: Install Firefox
        run: |
          choco install firefox

      - name: Run Selenium tests
        run:  mvn test -Dtest=SeleniumTest
